[http.middlewares]
    [http.middlewares.bastion-hosts.ipWhiteList]
        sourceRange = [
            "1.1.1.1",  # Server 1
        ]
 
[tcp.middlewares]
    [tcp.middlewares.bastion-hosts.ipWhiteList]
        sourceRange = [
            "1.1.1.1",  # Server 1
        ]
