version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.sftp.address=:2222/tcp"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.test.ca`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      
  sftpGo:
    image: "drakkan/sftpgo:latest"
    container_name: "sftpGo"
    expose:
      - "1111/tcp"
      - "2222/tcp"
    environment:  
      # Proxy Protocol
      - "SFTPGO_COMMON__PROXY_PROTOCOL=2"
      - "SFTPGO_COMMON__PROXY_ALLOWED=0.0.0.0"
      # SFTP
      - "SFTPGO_SFTPD__BINDINGS__0__PORT=2222"
      - "SFTPGO_SFTPD__BINDINGS__0__PROXY_ALLOWED=0.0.0.0"
      # HTTP
      - "SFTPGO_HTTPD__BINDINGS__0__PORT=1111"
      - "SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED=0.0.0.0"
    
      # Defender (similar concept as Fail2ban) — see https://github.com/drakkan/sftpgo/blob/main/docs/defender.md
      - "SFTPGO_COMMON__DEFENDER__ENABLED=true"
      - "SFTPGO_COMMON__DEFENDER__BAN_TIME=30"
      - "SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT=50"
      - "SFTPGO_COMMON__DEFENDER__THRESHOLD=15"
      - "SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME=30"
    labels:
      - "traefik.enable=true"
      - "traefuk.tcp.routers.sftpgo-tcp.entrypoints=sftp"
      - "traefik.tcp.routers.sftpgo-tcp.rule=HostSNI(`*`)"
      
      - "traefik.http.routers.sftpgo.entrypoints=web"
      - "traefik.http.routers.sftpgo.rule=Host(`sftpgo.test.ca`)"

